### ISSUE TITLE
moon not comptabile with tzdata

### ISSUE THREAD

**Issue by anildigital** [coingaming/moon#806]
Error 

```
$ mix compile
==> moon
Compiling 768 files (.ex)

== Compilation error in file lib/moon_web/examples/design/table_example/clickable_rows.ex ==
** (ArgumentError) cannot add -3599 second to ~U[2023-12-15 12:13:30.534707Z] (with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
    (elixir 1.14.4) lib/calendar/datetime.ex:1561: DateTime.add/4
    lib/moon_web/examples/design/table_example/clickable_rows.ex:19: anonymous fn/1 in :elixir_compiler_461.__MODULE__/1
    (elixir 1.14.4) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (elixir 1.14.4) lib/enum.ex:4299: Enum.reduce_range/5
    (elixir 1.14.4) lib/enum.ex:2472: Enum.map/2
    lib/moon_web/examples/design/table_example/clickable_rows.ex:15: (module)
```

Steps to reproduce

- Create a fresh Phoenix 1.7 project
```
 mix phx.new check_tz_issue
```

- Add following packages to mix.exs deps
```elixir
{:moon, "~> 2.79"},
{:tzdata, "~> 1.1"},
```

- Add following line after import Config line in config/config.exs (basic steps to install tzdata in any Phoenix https://github.com/lau/tzdata)

```elixir
config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
```

- Run (if you have compiled already)

```
rm -rf _build
mix compile
```

- shows following compilation error

```
mix compile
==> moon
Compiling 768 files (.ex)

== Compilation error in file lib/moon_web/examples/design/table_example/clickable_rows.ex ==
** (ArgumentError) cannot add -3599 second to ~U[2023-12-15 12:13:30.534707Z] (with time zone database Tzdata.TimeZoneDatabase), reason: :time_zone_not_found
    (elixir 1.14.4) lib/calendar/datetime.ex:1561: DateTime.add/4
    lib/moon_web/examples/design/table_example/clickable_rows.ex:19: anonymous fn/1 in :elixir_compiler_461.__MODULE__/1
    (elixir 1.14.4) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2
    (elixir 1.14.4) lib/enum.ex:4299: Enum.reduce_range/5
    (elixir 1.14.4) lib/enum.ex:2472: Enum.map/2
    lib/moon_web/examples/design/table_example/clickable_rows.ex:15: (module)
```

**Comment by phgrey** [comment]
not sure if `reason: :time_zone_not_found` is smth related to Moon, but all unnecessary  DateTime.add are removed

**Comment by phgrey** [comment]
https://github.com/coingaming/moon/pull/807
